apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: b9s3abplt-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-c175a581c0.04dg.p3.openshiftapps.com/rhtap/rhtap-qe:7c9d971f241c1e8062f817fb204818efe068dffe@sha256:4ceb666c6dea8b2f4dde8e6dbc5e13cc1dd71c6055ce1da286c3e8f63bb7f7a2
          name: container-image
